#!/bin/bash
#
# This script requires lcov to be installed
#

TESTS="test-decoder"

FLAVOR="release"

pushd `dirname $0` > /dev/null
COV_DIR="$PWD"
pushd .. > /dev/null
TEST_DIR="$PWD"
pushd .. > /dev/null
BASE_DIR="$PWD"
popd > /dev/null
popd > /dev/null
popd > /dev/null

# LCOV 1.10 has branch coverage disabled per default
LCOV_OPT="--rc lcov_branch_coverage=1"
GENHTML_OPT="--branch-coverage"

make GCOV=1 -C "$BASE_DIR" clean $FLAVOR
COV_FILES=
for t in $TESTS ; do
    pushd "$TEST_DIR/$t"
    TEST_COV="$PWD/build/$FLAVOR/$t.gcov"
    make GCOV=1 -C "$TEST_DIR/$t" clean $FLAVOR || exit 1
    build/$FLAVOR/$t || exit 1
    lcov $LCOV_OPT -c -i -d build/$FLAVOR -o "$TEST_COV" || exit 1
    lcov $LCOV_OPT -c -d build/$FLAVOR -b "$PWD" -o "$TEST_COV" || exit 1
    COV_FILES+="-a $TEST_COV"
    popd
done

FULL_COV="$COV_DIR/full.gcov"
SERVICE_COV="$COV_DIR/service.gcov"
rm -f "$FULL_COV" "$SERVICE_COV"
lcov $LCOV_OPT $COV_FILES -o "$FULL_COV" || exit 1
lcov $LCOV_OPT -e "$FULL_COV" "$BASE_DIR/src/*" -o "$SERVICE_COV" || exit 1
genhtml $GENHTML_OPT -t provisioning-service "$SERVICE_COV" --output-directory "$COV_DIR/results" || exit 1
